# Delivery

### Create your own EDA library: 

In this delivery the student will need to create its won library (module). The library must include the EDA functions we are seeing in class and you create. 

A python library is a ".py" file that contains python code.

There are some requirements: 

- EAch functionality must be done in functions.
- Each function must be general. It must be useful for the most of cases.
- Functions must not have repeated code. Each function must do something function.
- The library should import others libraries as numpy, pandas, ...
- Try to create a module ".py" for each type of functionalty. If you are creating visualizing funcions, then the functions will be in a "my_visualizing_functions_module.py", for example. If you are creating analysis functions, then they will be in a "my_analysis_functions_module.py", for example. 
- Each function must be well documented. It must explain the functionality and each function param. 
- The code must be done in a ".py" file. 

Delivery instructions:
- End date: 12/07/2020 23:59 
- Send to: 

    - clara.piniella@thebridgeschool.es
    - gabriel@thebridgeschool.es






In [1]:
import numpy

In [2]:
set([2, 2, 2, 1, 3, 3])

{1, 2, 3}

In [7]:
tuple_a = (1,2,3)
tuple_a.__hash__()

#es una "id" de los números o tuplas o listas, etc en términos matemáticos

2528502973977326415

In [11]:
tuple_a

(1, 2, 3)

In [12]:
import numpy as np 

np.arange(start=1, stop=10, step=3)

array([1, 4, 7])

In [15]:
 arr1 = np.array([1, 2, 3], dtype=np.float64)
 arr1

array([1., 2., 3.])

In [16]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2

array([1, 2, 3], dtype=int32)

In [7]:
import your_module as ym
x = [2, 3, 4, 5]
ym.revert(x)



[5, 4, 3, 2]

In [5]:
import numpy as np

In [6]:
import your_module as ym 
z = np.array([2, 3, 4, 5])
ym.tamano(z)


The array =  [2 3 4 5]
